### ISSUE TITLE
Support Lazy Loading Videos from Google Drive

### ISSUE THREAD

**Issue by jeffmcneill** [kevinweber/lazy-load-for-videos#10]
Google Drive has a video player and can stream video. This can be done in an iframe or as an object. Would be great to have the same lazyload support for Google Drive (there is some blocking code in the player currently, that slows down page load).

**Comment by kevinweber** [comment]
How is that related to my WordPress plugin? Or are you suggesting that Google should implement (better) lazy loading into Google Drive?

Closing this topic for now because I don't think this is related enough to the WordPress plugin.

**Comment by jeffmcneill** [comment]
The plugin supports lazy loading YouTube and Vimeo. This issue is to request that Google Drive also be supported, like with support for YouTube and Vimeo. The video player is very similar to the YouTube player. Not sure how this is confusing.
