### ISSUE TITLE
video links appear in the content of the posts instead of iframes

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [kevinweber/lazy-load-for-videos#14]
Thank you very much for the plugin.
I noticed that the plugin only lazy load in the excerpts not in the content of the posts. Additionally the plugin shows video links in the content of the posts instead of iframes

**Comment by kevinweber** [comment]
This sounds like your theme doesn't support oembed, or your theme uses Ajax to load the content. If the theme uses Ajax, the issue might be fixed with the latest version of this plugin (v2.7.0).
