### ISSUE TITLE
youtube "t=XX" parameter applying on preroll not on main video

### ISSUE THREAD

**Issue by Jez86** [kevinweber/lazy-load-for-videos#17]
When I tried to load video not from the beginning using url like :

https://youtu.be/XXXXXXXX?t=XX

the t parameter is applying on the preroll video (if existing) not on the main video of the playlist.

I tried to make some modifications in /modules/lazyload-youtube/index.js but I didn't had any result...

**Comment by kevinweber** [comment]
@Jez86 From my understanding, it's not possible using Youtube's URL schema to define when specific videos of a playlist start, see: https://webapps.stackexchange.com/questions/119264/how-to-set-start-end-time-for-every-video-on-playlist-in-youtube. I'm using Youtube's playlist feature to play the preroll video before the main video.

I could imagine it's possible to implement some custom logic into this WordPress plugin to solve what you're asking for. However, I don't plan on implementing this logic in the foreseeable future.
