### ISSUE TITLE
consistent error code

### ISSUE THREAD

**Issue by suziehk** [kevinweber/lazy-load-for-videos#18]
PHP Fatal error:  Cannot declare class Lazyload_Videos_Youtube, because the name is already in use in /home/xxxx/public_html/wp-content/plugins/lazy-load-for-videos/frontend/class-youtube.php on line 5

excuse my ignorance but can't find a way to remove this error.

**Comment by kevinweber** [comment]
@suziehk Can you search your wp-content directory for `Lazyload_Videos_Youtube`? It looks like some other plugin or a theme is using this class name. There can only be one such class in your WordPress directory. If you find `Lazyload_Videos_Youtube`, a solution could be to disable/remove one of the plugins/themes with the duplicate class.
