### ISSUE TITLE
Appended "#at=0" causes 404 for Vimeo thumbnails

### ISSUE THREAD

**Issue by kevinweber** [kevinweber/lazy-load-for-videos#24]
If the Vimeo URL is https://vimeo.com/316593453#at=0 instead of https://vimeo.com/316593453 (without the hash), a 404 gets thrown in the network panel and now thumbnail shows up.

Make sure to strip out any parameters when requesting the thumbnail so we don't get an error.

**Comment by JSchork** [comment]
Hi, we experienced the same problem, but with normal YouTube URLs. The thumbnail of some videos is not shown properly, even though we inserted the plain URL without #at=0.

Here, you can find an example: https://gartenprimus.de/nagelschuhe

The inserted YouTube URL is: https://www.youtube.com/watch?v=yXm2Q8nVgP0

**Comment by kevinweber** [comment]
The Vimeo thumbnail issue is resolved with version 2.7.8. I haven't looked at the Youtube issue yet but I believe it'll be resolved as part of the v3 updates.

**Comment by kevinweber** [comment]
I'm closing this ticket as it was opened for the Vimeo issue and not the Youtube issue. Please file a new ticket for just the Youtube case if still relevant.
