### ISSUE TITLE
Satisfy VideoObject schema requirements

### ISSUE THREAD

**Issue by kevinweber** [kevinweber/lazy-load-for-videos#29]
From @Play_Book_Of_Ra [via Twitter](https://twitter.com/Play_Book_Of_Ra/status/1141718665500528640):
> Very useful plugin, but unfortunately it's creating some schema errors on the page see image. some properties are missing.

![D9gzEkVXYAI2lTc](https://user-images.githubusercontent.com/2785791/59958833-b1f6f080-9461-11e9-8bdf-9ec6582dc72b.png)

**Comment by udarts** [comment]
Is this already being fixed? It's been a while since Jun 22.

**Comment by kevinweber** [comment]
Yes, this has been resolved with v2.7.6. See also: https://wordpress.org/support/topic/error-in-structured-data-3/
