### ISSUE TITLE
Demo is missing CSS in Firefox

### ISSUE THREAD

**Issue by scheinercc** [kevinweber/lazy-load-for-videos#43]
It seems like the stylesheets are not getting loaded in Firefox on https://www.kweber.com/lazy-load-videos/

**Comment by kevinweber** [comment]
@scheinercc Thanks for letting me know!
I just fixed the issue: It wasn't related to the WordPress plugin but instead it was caused by my theme where I hadn't properly implemented lazy-loading of stylesheets.

**Comment by scheinercc** [comment]
That was quick! I knew it wasn't the plugin, but I couldn't find an email address to let you know, so I misused Github ;)
I guess it had to do with this!? https://web.dev/defer-non-critical-css/
Mind telling me what bugged Firefox? Was it the ` onload="this.onload=null;this.rel='stylesheet'"`?

**Comment by kevinweber** [comment]
@scheinercc I changed the link to `<link rel='preload stylesheet' as='style' id='$handle' href='$href' />` (added "stylesheet") and haven't actually verified if lazy-loading works. At this point, it doesn't really matter to my website, though, but I surely want it to work in FF.

**Comment by scheinercc** [comment]
Thanks for sharing :) Will keep this in mind. Might be due to: https://bugzilla.mozilla.org/show_bug.cgi?id=1626997

**Comment by scheinercc** [comment]
This might of interest for you as well: https://www.filamentgroup.com/lab/load-css-simpler/
also: https://stackoverflow.com/questions/32759272/how-to-load-css-asynchronously/46750893#46750893
also: https://caniuse.com/#search=preload
