### ISSUE TITLE
Add page/css class exclusions?

### ISSUE THREAD

**Issue by Supaiku** [kevinweber/lazy-load-for-videos#44]
Hello,

It seems there's no way to do this, could this feature be added?

thank you,
CJ

**Comment by kevinweber** [comment]
I don't plan to add new features. Feel free to submit a PR.
A while back I added a similar feature to https://github.com/kevinweber/wbounce. You could check out that plugin for inspiration on how to exclude pages from loading the Lazy Load for Videos script.
