### ISSUE TITLE
Thumbnail blurred on big size

### ISSUE THREAD

**Issue by Welldoor** [kevinweber/lazy-load-for-videos#58]
Hey,

can you please have a short look at https://wellbeingstiftung.de/ ?

The site speed improved a lot with your plugin and the bunch of vimeo videos!!

But here comes the problem, the first thumbnail is blurred. It worked before thou.

I activated/deactivated W3total Cache and EWWW Image Optimizer.

I updated to current version yesterday, but I don't think that made the difference?!

In the end, it just loads https://i.vimeocdn.com/video/1124080391_295x166 which is way to small for that location of the first video.

Any idea what to do here?

![lazyload](https://user-images.githubusercontent.com/76523622/117791937-218b4a00-b24b-11eb-8f47-d9d0cb980d33.PNG)

**Comment by kevinweber** [comment]
Ha, that's strange. Thanks for reporting the issue and for providing helpful details (link, screenshot).

It looks like either Vimeo or oEmbed started to no longer respond with thumbnails that have a file extension. I just published v2.15.2 with a fix. Let me know if that fixed it.

**Comment by Welldoor** [comment]
Works! Thanks a lot!
