### ISSUE TITLE
Switch to WordPress default styling

### ISSUE THREAD

**Issue by wormeyman** [kevinweber/lazy-load-for-videos#59]
1. https://make.wordpress.org/core/2019/04/02/admin-tabs-semantic-improvements-in-5-2/
2. https://nimblewebdeveloper.com/blog/add-tabs-to-wordpress-plugin-admin-page

I'm thinking of submitting a PR for this let me know if that would be appreciated.

**Comment by kevinweber** [comment]
Hi @wormeyman, yes, the current UI is rather antique and I'd love and appreciate your contribution!

**Comment by wormeyman** [comment]
Hi @kevin, I unfortunately could not get the NPM modules to install. I think this is because i have an M1 Mac. I understand if you do not have the time to debug my issue. It appears to be related to lib-sass.

**Comment by kevinweber** [comment]
What's the error? I'd guess that many others on the internet have had the issue before and the fix should be easy. Maybe the NPM dependencies need to be updated? I just did that: updated various CSS-related dependencies and pushed the changes to the master branch. Let me know if it's still an issue.

**Comment by wormeyman** [comment]
Thanks for the dependency updates everything installed successfully this time.
