### ISSUE TITLE
Plugin throws multiple PHP notices

### ISSUE THREAD

**Issue by markhowellsmead** [kevinweber/lazy-load-for-videos#63]
`Notice: Undefined property: stdClass::$title in […]/wp-content/plugins/lazy-load-for-videos/src/php/class-admin-options.php on line 106`

`Notice: Undefined property: stdClass::$thumbnail_url in […]/wp-content/plugins/lazy-load-for-videos/src/php/class-admin-options.php on line 109`

`Notice: Undefined property: stdClass::$title in […]/wp-content/plugins/lazy-load-for-videos/src/php/class-admin-options.php on line 114`

`Notice: Undefined property: stdClass::$title in […]/wp-content/plugins/lazy-load-for-videos/src/php/class-admin-options.php on line 106`

`Notice: Undefined property: stdClass::$thumbnail_url in […]/wp-content/plugins/lazy-load-for-videos/src/php/class-admin-options.php on line 109`

`Notice: Undefined property: stdClass::$title in […]/wp-content/plugins/lazy-load-for-videos/src/php/class-admin-options.php on line 109`

`Notice: Undefined property: stdClass::$title in […]/wp-content/plugins/lazy-load-for-videos/src/php/class-admin-options.php on line 114`

**Comment by kevinweber** [comment]
It looks like that's related to a specific Vimeo embed. Can you share the Vimeo URL(s) you're using? And on what page is this error thrown, e.g. on a published blog post or when in the blog post editor or when on the plugin's admin panel?

**Comment by markhowellsmead** [comment]
That's for https://vimeo.com/405106808. It's on a single custom post type view, where the code is loaded using `wp_oembed_get('https://vimeo.com/405106808, ['width' => 736, 'height' => 415])`.

**Comment by kevinweber** [comment]
Sounds surprising that wp_oembed_get doesn't give you the same details… I'm not too familiar with this. Could you instead run the `run_shortcode` and `autoembed` on your custom post type? Something like this where I enable oEmbeds for widgets: https://github.com/kevinweber/lazy-load-for-videos/blob/master/src/php/inc/support_for_widgets.php

**Comment by markhowellsmead** [comment]
`wp_oembed_get` returns the complete, finished HTML delivered the remote server. The site/theme/installation doesn't support shortcodes or widgets, so your suggestion wouldn't have any effect. It works on many other Vimeo videos, and in fact, the image replacement works fine. I'd suggest adding checks to ensure that the `stdClass` contains the indicated properties. 

(Requires the null coalescing operator added in PHP 7.0, but you get the idea.)

```
$play_title_text = sprintf(esc_attr__( 'Play video &quot;%s&quot;', LL_TD ),
	$data->title ?? ''
);
```

**Comment by kevinweber** [comment]
Okay good, I'm happy to have such a solution. Would you mind putting up a PR with the fixes? Then you'll be sure that it's going to work for you. Otherwise I'll need to see when I can make time on one of the next weekends.

One note though: Let's not use the null coalescing operator because many WordPress sites aren't using PHP 7 yet. The required minimum version is just 5.6.20 or so.

**Comment by markhowellsmead** [comment]
The PR referenced by #65 resolves this.
