### ISSUE TITLE
Some videos not showing their thumbnails

### ISSUE THREAD

**Issue by jimcasedo** [kevinweber/lazy-load-for-videos#74]
Hi

Plugin working GREAT except for one thing. 

Have installed on WP 6.2 (appreciate that the WP is telling me that the plugin is not tested on this version) and everything is lazy loading as expected (am only using this for Vimeo videos), except for the video on the homepage is refusing to show it's thumbnail. I've tried uploading a new thumbnail etc, but it's stubbornly not playing ball.

Is there a certain format for the thumbnail or some such? All the other videos are showing their thumbnails, but not the most important one!

Did I miss something? (I've currently substituted the required video for another, until I get this fixed).

v. happy to share urls etc if needed.

Jim

**Comment by kevinweber** [comment]
On the plugin's admin page, there's a setting: Thumbnail quality. Does the thumbnail appear if you some different setting quality setting?

**Comment by jimcasedo** [comment]
Many thanks for getting back to me so quickly. Unfortunately that hasn't worked. It's very odd. It seems to be more to do with which video it is, rather than the type of thumbnail. I'll continue to have a play. Any other suggestions?

**Comment by jimcasedo** [comment]
UPDATE: I got nowhere with the videos that weren't working, so I downloaded one of them off the Vimeo site and then uploaded it again, and hey presto, it works...!

Coffee coming up Kevin...
